### ISSUE TITLE
How to make http request to stellar

### ISSUE THREAD

**Issue by whysetiawan** [pigzbe/react-native-stellar-sdk#1]
I want to create stellar account. I see stellar docs but it seems should make http request manually. I've tried using [request](https://github.com/request/request) library but it requiring [crypto](https://nodejs.org/api/crypto.html) . I've tried using axios as well but the request got 400 status message.

here is my source code :

```
Stellar.Keypair.randomAsync().then(keypair => {
      const publicKey = keypair.publicKey();
      const secretKey = keypair.secret();
      axios({
        url: 'http://friendbot.dijexi.com:8001',
        method: 'GET',
        qs: { addr: publicKey }
      })
      .then((res) => console.log(res))
      .catch((err) => console.log(err.response))
  });
```

**Comment by ianmcgregor** [comment]
Hi @whysetiawan,

You can use the standard fetch API in React Native. Also I'd suggest trying it with the official stellar.org testnet first:

```javascript
fetch(`https://horizon-testnet.stellar.org/friendbot?addr=${keypair.publicKey()}`)
```

Note that friendbot is only for creating and funding testnet accounts. Aside from the async randomBytes this lib works the same as the regular js sdk so you can refer to the official docs.
